"""Pydantic data models for agent schema validation and LLM interactions."""

from pydantic import BaseModel, ConfigDict, Field


class InterstitialEntry(BaseModel):
    """Schema representing an interstitial journal entry with extracted metadata and atomic note options."""

    timestamp: str = Field(
        description="Timestamp of the entry in ISO 8601 or HH:MM format.",
    )
    category: str = Field(
        default="general",
        description="Category classification of the entry (e.g. log, task, discovery, thought).",
    )
    content: str = Field(
        description=(
            "Raw or processed markdown text content of the interstitial entry. "
            "For tasks (category='task'), format with Obsidian Tasks syntax: "
            "'- [ ] {Task Name} ➕ YYYY-MM-DD 📅 YYYY-MM-DD'."
        ),
    )
    extracted_tags: list[str] = Field(
        default_factory=list,
        description="List of tags extracted from the content (e.g. ['#pkm', '#idea']).",
    )
    extracted_wikilinks: list[str] = Field(
        default_factory=list,
        description="List of Obsidian wikilinks extracted from the content (e.g. ['[[Project]]']).",
    )
    requires_atomic_note: bool = Field(
        default=False,
        description="Flag indicating whether an independent atomic note should be generated.",
    )
    atomic_note_title: str | None = Field(
        default=None,
        description="Title of the standalone atomic note if requires_atomic_note is True.",
    )
    atomic_note_content: str | None = Field(
        default=None,
        description="Markdown body content of the standalone atomic note if requires_atomic_note is True.",
    )
    due_date: str | None = Field(
        default=None,
        description="Optional due date for tasks formatted as 'YYYY-MM-DD'.",
    )
    dataview_fields: dict[str, str] = Field(
        default_factory=dict,
        description="Inline Dataview key-value properties formatted as [key:: value] (e.g. {'category': 'Log', 'source': 'Telegram'}).",
    )
    block_id: str | None = Field(
        default=None,
        description="Optional block identifier anchor without leading carat (e.g. 'log-1030', 'task-01') for Obsidian block transclusion ^block-id.",
    )
    callout_type: str | None = Field(
        default=None,
        description="Optional Obsidian callout type (e.g. 'NOTE', 'WARNING', 'TIP', 'IMPORTANT', 'CAUTION') for alerts or summaries.",
    )

    model_config = ConfigDict(
        str_strip_whitespace=True,
        use_enum_values=True,
    )


class QueryRequest(BaseModel):
    """Schema for knowledge base query requests."""

    query: str = Field(
        description="Natural language query or question from the user.",
    )
    top_k: int = Field(
        default=5,
        description="Maximum number of context chunks or search results to retrieve.",
    )
    filters: dict[str, str] | None = Field(
        default=None,
        description="Optional key-value filters to restrict vector search results.",
    )

    model_config = ConfigDict(
        str_strip_whitespace=True,
    )


class QueryResponse(BaseModel):
    """Schema for knowledge base query responses."""

    query: str = Field(
        description="Original natural language query string.",
    )
    answer: str = Field(
        description="Synthesized answer generated by the LLM agent based on vault context.",
    )
    sources: list[str] = Field(
        default_factory=list,
        description="List of Obsidian file paths or wikilinks referenced to form the answer.",
    )
    context_chunks: list[dict[str, str]] = Field(
        default_factory=list,
        description="Retrieved vault context chunks with metadata used in answering.",
    )

    model_config = ConfigDict(
        str_strip_whitespace=True,
    )
